---
abstract: "Object-oriented interface to INFOnline's Website Controlling Cockpit (WCC)."
author:
  - 'Tobias Kremer <tkremer@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-INFOnline
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  LWP::UserAgent: 0
  Moose: 0.88
  Text::CSV: 1.10
  DateTime: 0
  namespace::autoclean: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
